#ifndef SUPERZ80_CORE_CONFIG_H
#define SUPERZ80_CORE_CONFIG_H

#define SUPERZ80_APP_NAME "Super_Z80"
#define SUPERZ80_VERSION_MAJOR 0
#define SUPERZ80_VERSION_MINOR 0
#define SUPERZ80_VERSION_PATCH 0

#endif
