function(superz80_enable_warnings target as_errors)
  if (MSVC)
    target_compile_options(${target} PRIVATE /W4)
    if (${as_errors})
      target_compile_options(${target} PRIVATE /WX)
    endif()
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    if (${as_errors})
      target_compile_options(${target} PRIVATE -Werror)
    endif()
  endif()
endfunction()
